language: go
os:
  - linux
  - osx
arch:
  - AMD64
  - ppc64le
go:
  - 1.15
  - tip
sudo: false
addons:
  apt:
    packages:
      - libcap-dev
install:
  - mkdir -p $HOME/gopath/src/gopkg.in/hlandau
  - mv $HOME/gopath/src/github.com/hlandau/service $HOME/gopath/src/gopkg.in/hlandau/service.v2
  - cd $HOME/gopath/src/gopkg.in/hlandau/service.v2
  - go get gopkg.in/hlandau/service.v2
